/************************************************************/
/*   Name-Surname: Korel Chairoula - 150140910              */
/*   e-mail      : korel_hayrullah@hotmail.com              */
/*   Course Name : BIL 105E - Int to Sci & Eng Computing C  */
/*   Term        : Spring 2015-2016                         */
/*   Assignment  : Homework #2                              */
/************************************************************/
#include <stdio.h>

int range1_100 = 0,range101_200 = 0,range201_300 = 0,range301_400 = 0,range401_500 = 0,i;//global defined ranges and i

void MID_RNG(long *number);//function prototype
void LSD_RNG(long *number);//function prototype
void take_samples(long *number);//function prototype
void print_histogram(int range1_100,int range101_200, int range201_300, int range301_400, int range401_500);//function prototype

int main(){//main function
  int control, num_samples;
  long seed;
  printf("Which PRNG Algorithm?\n1.MID-PRNG\n2.LSD-PRNG\n");
  scanf("%d",&control);
  printf("Enter the seed\n");
  scanf("%ld",&seed);
  printf("Enter Number of Samples\n");
  scanf("%d",&num_samples);

  if (control == 1){ //if statement for controlling which PRNG Algorithm will be chosen
    for (i = 0; i < num_samples;i++){//for loop until num_samples
      MID_RNG(&seed);//MID_RNG function
      take_samples(&seed);//take_samples funcion
    }//end of for
    printf("%d random numbers were generated by using MID-PRNG:\n", num_samples);
    print_histogram((range1_100 * 100)/num_samples, (range101_200 * 100)/num_samples, (range201_300 * 100)/num_samples, (range301_400 * 100)/num_samples, (range401_500 * 100)/num_samples);//print_histogram function
    puts("");
  }//end of if
  else if (control == 2){ //if else statement for controlling which PRNG Algorithm will be chosen
    if (seed % 2 != 0 && seed % 10 != 5){//checks whether the seed entered by the user does not end with 5 and is not even
      for(i =0;i < num_samples;i++){ //for loop until num_samples
        LSD_RNG(&seed);// LSD_RNG function
        take_samples(&seed);//take_samples function
      }//end of for
      printf("%d random numbers were generated by using LSD-PRNG:\n",num_samples);
      print_histogram((range1_100 * 100)/num_samples, (range101_200 * 100)/num_samples, (range201_300 * 100)/num_samples, (range301_400 * 100)/num_samples, (range401_500 * 100)/num_samples); //print_histogram function
      puts("");
    }
    else // else statement which warns the user whether the number is even or ends with 5
      printf("The number you entered is even or ends with 5. Try again.\n");
  }//end of else if

  else // else statement which warns the user when the control number is not entered correct(1 for MID_RNG || 2 for LSD_RNG)
    printf("Wrong number entered try again.\n");


  return 0;
}//end of main


void MID_RNG(long *number){//MID_RNG function
  long square;
  square = *number * *number;

  if (square >= 1000000000) //checks for 10 digits
    *number = (square % 100000000) / 1000;
  else if (square >=100000000) //checks for 9 digits
    *number = (square % 10000000) / 100;
  else if (square >=10000000) //checks for 8 digits
    *number = (square % 10000000) / 100;
  else if (square >=1000000) //checks for 7 digits
    *number = (square % 1000000) / 10;
  else if (square >=100000) //checks for 6 digits
    *number = square / 10;
  else  //checks for 5 and remaining digits
    *number = square;
}//end of MID_RNG function


void LSD_RNG(long *number){//LSD_RNG function
  *number = (*number * 73) % 100000; //multiplies the number with 73 and takes out the 5 digits from left to right
}//end of LSD_RNG function

void take_samples(long *number){//take_samples function
  int sample;
  sample = (*number % 500) + 1;

  if (sample <= 100) //increments range 1 to 100 by one
    range1_100++;
  else if (sample <=200) //increments range 101 to 200 by one
    range101_200++;
  else if (sample <=300) //increments range 201 to 300 by one
    range201_300++;
  else if (sample <=400) //increments range 301 to 400 by one
    range301_400++;
  else  //increments range 401 to 500 and the remaining ones by one,but since it can not be above 500 it is in range 401 to 500
    range401_500++;
}//end of take_samples function

void print_histogram(int range1_100,int range101_200, int range201_300, int range301_400, int range401_500){//print_histogram function

  printf("  1..100:");
  for (i = 0; i < range1_100; i++) //printing histogram for range 1 to 100 which the ranges are taken from take_samples fuction stored globally
    printf("*");
  printf("(%d%c)",range1_100,'%');
  printf("\n101..200:");

  for (i = 0; i < range101_200;i++) //printing histogram for range 101 to 200 which the ranges are taken from take_samples fuction stored globally
    printf("*");
  printf("(%d%c)",range101_200,'%');
  printf("\n201..300:");

  for (i = 0; i < range201_300;i++) //printing histogram for range 201 to 300 which the ranges are taken from take_samples fuction stored globally
    printf("*");
  printf("(%d%c)",range201_300,'%');
  printf("\n301..400:");

  for (i = 0; i < range301_400;i++) //printing histogram for range 301 to 400 which the ranges are taken from take_samples fuction stored globally
    printf("*");
  printf("(%d%c)",range301_400,'%');
  printf("\n401..500:");

  for (i = 0; i < range401_500;i++) //printing histogram for range 401 to 500 which the ranges are taken from take_samples fuction stored globally
    printf("*");
  printf("(%d%c)",range401_500,'%');
  printf("\n");
}//end of print_histogram function
